export const DEFAULT_CONFIG = {
  maxPages: 100,
  maxDepth: 5,
  concurrency: 5,
  delayMs: 0,
  timeout: 15000,
  retries: 2,
  userAgent: 'SiteAuditTool/1.0 (+https://github.com/) Node.js',
  respectRobots: true,
  includeSubdomains: false,
  includePatterns: [],
  excludePatterns: [],
  useSitemap: true,
  checkExternalLinks: false,
  linkCheckConcurrency: 10,
  accessibility: false,
  accessibilityPages: 5,
  lighthouse: false,
  lighthousePages: 3,
  outputDir: './site-audit-report',
  formats: ['html', 'json'],
  failUnder: null,
  quiet: false,
  verbose: false
};
